on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-latest
          - ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: getong/mongo-action@v1.1
        with:
          mongo version: '4.2-bionic'
          host port: 27017
          mongo username: 'testuser'
          mongo password: 'testpass'
      - run: cat /etc/mongo.conf
        # - run: mongo -u testuser -p testpass --eval "printjson(db.serverStatus())"
        shell: bash
